name: Extract bikes stolen

on:
    schedule:
      - cron: "*/15 * * * *"
   
jobs:
    build:
        runs-on: ubuntu-latest
        container: python:3

        steps:
          - uses: actions/checkout@v2
            with:
              token: ${{ secrets.GH_ACCESS_TOKEN }} 
              # Optional commit user and author settings
              commit_user_name: ManuekBanza # defaults to "github-actions[bot]"
              commit_user_email: manuelbanza@hotmail.com # defaults to "github-actions[bot]@users.noreply.github.com"
    
          - name: Configure pt_PT locale
            run: |
              apt-get update -y && apt-get install -y locales && echo "pt_PT.UTF-8 UTF-8" | tee -a /etc/locale.gen && locale-gen pt_PT.UTF-8
          - name: Configure pt_PT (Europe/Lisbon) timezone
            run: |
              ln -fs /usr/share/zoneinfo/Europe/Lisbon /etc/localtime && dpkg-reconfigure --frontend noninteractive tzdata
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              python -m pip install -r requirements.txt
          - name: Scrap bikes stolen
            run: |
              python get_lisbon_airport_flights.py
          - name: Commit changes
            uses: stefanzweifel/git-auto-commit-action@v4.1.1
            with:
                commit_message: Update bikes stolen
                branch: ${{ github.head_ref }}

